# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CPANPLUS-Daemon
version:      0.01
version_from: lib/CPANPLUS/Daemon.pm
installdirs:  site
requires:
    CPANPLUS:                      0.051
    CPANPLUS::Shell::Default:      0.051
    Getopt::Std:                   0
    IO::String:                    0
    Locale::Maketext::Simple:      0
    Object::Accessor:              0.02
    Params::Check:                 0.22
    Poe:                           0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
